#!/usr/bin/env python

Import("env")
Import("env_modules")

env_bluetooth = env_modules.Clone()

if env["platform"] == "macos":
    env_bluetooth.add_source_files(env.modules_sources, "register_types.cpp")
    env_bluetooth.add_source_files(env.modules_sources, "bluetooth_macos.mm")
